from .burmese_python import BurmesePython
from .copperhead import Copperhead
from .corn_snake import CornSnake
from .legless_lizard import LeglessLizard
from .rattlesnake import Rattlesnake
from .alligator import Alligator
from .axolotl import Axolotl
from .carp import Carp
from .crocodile import Crocodile
from .sea_snake import SeaSnake
from .alpaca import Alpaca
from .donkey import Donkey
from .goat import Goat
from .llama import Llama
from .monkey import Monkey